name: Deploy website

on:
  pull_request:
    branches: [main]

env:
  BRANCH_NAME: ${{ github.ref_name }}

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: 'Test'
        run: npx vitest --coverage.enabled true

      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
